# Generated by Django 5.1.6 on 2025-02-20 11:18

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reg_date',
            field=models.CharField(default=datetime.datetime(2025, 2, 20, 16, 18, 4, 591994), editable=False, max_length=26),
        ),
    ]
