# Generated by Django 5.1.6 on 2025-02-20 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.CharField(max_length=20)),
                ('query', models.TextField()),
                ('url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
            },
        ),
    ]
