# Generated by Django 5.1.6 on 2025-02-20 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.UUIDField()),
                ('comment', models.TextField()),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_comments', to='users.profile')),
            ],
            options={
                'verbose_name': 'Ad Comment',
                'verbose_name_plural': 'Ad Comments',
            },
        ),
    ]
